version: "3.8"
services:
  front:
    build: .
    container_name: movasagh-customer
    env_file:
      - .env
    volumes:
      - ${FRONT_ROOT}/static:/usr/src/movasagh-customer/static
    command: tail -f /dev/null
